apiVersion: v1
kind: Service
metadata:
  name: default/backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8080
      name: https
